### PR TITLE
Sort and hash bigbrain intensity profiles by coordinates

### PR DESCRIPTION
**Pull request by AhmetNSimsek**
Should fix https://github.com/FZJ-INM1-BDA/siibra-python/issues/295. Further testing is required.

### CODE REVIEW

**Comment by AhmetNSimsek** [comment]
The ordering logic works for every new sesion but different sessions still shows the ordering differently. This is a problem since it is not produce reproducible ordering (the values are still the same) and `siibra-api` is stateless.

Suggested solution: employ a different ordering principle like euclidean norm as the current coordinate comparison is very limited.

**Comment by xgui3783** [comment]
Imo, not just an issue for siibra API. Notebooks can't be repeated either.

**Comment by AhmetNSimsek** [comment]
> Imo, not just an issue for siibra API. Notebooks can't be repeated either.

Indeed, that is what I meant by "it does not produce a reproducible ordering (the values are still the same)"

**Comment by AhmetNSimsek** [comment]
A better solution found https://github.com/FZJ-INM1-BDA/siibra-python/issues/295#issuecomment-1730966308

**Pull request closed without merging**
