### PR TITLE
Refactor ZipfileConnector and ZipfileRequest

### PR DESCRIPTION
**Pull request by AhmetNSimsek**
To allow more lazy loading from zipfiles. See #389 and #402

Note: Use `zipConnRefactorAdjustments` branch of siibra-configurations for testing

### CODE REVIEW

**Comment by AhmetNSimsek** [comment]
As of 1bc82bd4e0f02ecd603ef35098ccaffb6b43b247 the requested features are achieved. However, when the average connectivity matrix is requested, it is very slow. Any ideas @xgui3783?

**Comment by AhmetNSimsek** [comment]
Note: `requests.get(url, stream=True)` caches the whole zip to memory. So calling several files implies downloading the zipfile to memory several times.
Considering implementing a 3rd party zip requester. A good candidate: https://github.com/gtsystem/python-remotezip

**Comment by xgui3783** [comment]
does not fix https://github.com/FZJ-INM1-BDA/siibra-python/issues/389, if it downloads the entire zip file.

**Comment by AhmetNSimsek** [comment]
Stale. A new version will be created for v0.5_dev

**Pull request closed without merging**
