### PR TITLE
Reformat `feature.name` and reintorudce `data` and `plot()` for `CompoundFeature`s

### PR DESCRIPTION
**Pull request by AhmetNSimsek**
- See #417 for the conversation on feature names.
- Averaged `data` and averaged graphs decided to be added in the dev meeting on 22.02.2024

Please use https://github.com/FZJ-INM1-BDA/siibra-configurations/tree/use_v04_feature_ids for configuration to test.

### CODE REVIEW

**Comment by xgui3783** [comment]
note: waiting on me (@xgui3783 ) to create a preview viewer/api instance

**Comment by xgui3783** [comment]
additional regression not covered by tests

some features now have duplicated ids

sample code:

```python
import siibra

siibra.cache.clear()

region = siibra.get_region("cortical layer", "1 left")

f, = siibra.features.get(region, "cell density profile")
print(len([_ for _ in f]), len({_.id for _ in f})) # prints 5 3
```

**Comment by xgui3783** [comment]
@AhmetNSimsek are the new commits meant to address https://github.com/FZJ-INM1-BDA/siibra-python/pull/568#issuecomment-1966356183 ?

**Comment by AhmetNSimsek** [comment]
> @AhmetNSimsek are the new commits meant to address [#568 (comment)](https://github.com/FZJ-INM1-BDA/siibra-python/pull/568#issuecomment-1966356183) ?

Indeed! I forgot to ping you, sorry.

**Pull request merged**
