### PR TITLE
feat: improve the response time of (ebrains) features

### PR DESCRIPTION
**Pull request by xgui3783**
This PR does two things to improve the loading time of feature extractor(s):

- reuse feature extractor (currently, each call to `atlas.get_features` results the instantiation of a new feature extractor)
- (for `EbrainsRegionalFeature` implements static method `get_cache`, which can be called ahead of time to further improve response time)

This should result in drastic improvement in:

- calling `get_feature`, especially:
  - repeated calling `get_feature` on same modality
  - if modality is ebrainsfeatures
  - if modality is ebrainsfeatures, and `get_cache` is called prior to calling `get_feature`

I will paste some performance comparison in the comments

---

**nb**

this PR also changes the way users should instantiate feature extractors.

Instead of passing the entire atlas object, one must explicitly pass parcellation and region as positional arguments, if required. The feature extractor will raise an exception if a positional argument is required, but not supplied.

This should allow caching of extractors to function properly.

### CODE REVIEW

**Comment by xgui3783** [comment]
the test script is:

```python
import time
import siibra as sb

def get_fp1_hoc1_left(atlas):
    atlas.select_region('hoc1 left')
    f1=atlas.get_features(sb.modalities.EbrainsRegionalDataset)
    atlas.select_region('fp1 left')
    f2=atlas.get_features(sb.modalities.EbrainsRegionalDataset)
    return [f1, f2]

def get_fp1_hoc1_right(atlas):
    atlas.select_region('hoc1 right')
    f1=atlas.get_features(sb.modalities.EbrainsRegionalDataset)
    atlas.select_region('fp1 right')
    f2=atlas.get_features(sb.modalities.EbrainsRegionalDataset)
    return [f1, f2]

def without_cache():
    atlas=sb.atlases.MULTILEVEL_HUMAN_ATLAS

    sb.retrieval.clear_cache()
    start_time = time.time()
    get_fp1_hoc1_left(atlas)
    print("--- without cache: %s seconds ---" % (time.time() - start_time))

    start_time=time.time()
    get_fp1_hoc1_right(atlas)
    print("--- without cache again: %s seconds ---" % (time.time() - start_time))

def with_cache():

    atlas=sb.atlases.MULTILEVEL_HUMAN_ATLAS
    sb.retrieval.clear_cache()
    start_time_0 = time.time()
    EbrainsRegionalFeatureCls=sb.features.classes[sb.modalities.EbrainsRegionalDataset]
    EbrainsRegionalFeatureCls.get_cache()
    
    start_time = time.time()
    get_fp1_hoc1_left(atlas)
    print("--- cache0: %s seconds ---" % (time.time() - start_time_0))
    print("--- cache1: %s seconds ---" % (time.time() - start_time))

    start_time=time.time()
    get_fp1_hoc1_right(atlas)
    print("--- with cache again: %s seconds ---" % (time.time() - start_time))

```

output is:

```sh
# current HEAD at 9404f126329e036cb9be7f740af7472ee6c2ac22
--- without cache: 34.37005639076233 seconds ---
--- without cache again: 22.192644596099854 seconds ---

# this PR
--- without cache: 26.56493639945984 seconds ---
--- without cache again: 0.018674135208129883 seconds ---

--- cache0: 23.2584171295166 seconds ---
--- cache1: 21.28674578666687 seconds ---
--- with cache again: 0.015386581420898438 seconds ---
```

**Comment by xgui3783** [comment]
Perf update:

```sh
--- cache0: 2.651280403137207 seconds ---
--- cache1: 0.11670804023742676 seconds ---

--- with cache again: 0.014444589614868164 seconds ---
```

list comprehension is truly a magical gift.

**Comment by xgui3783** [comment]
One more update:

```sh
# nb the preheat caches **ALL** available parcellations
# they can be preheated separately to reduce the preheat 
--- preheat-1: 372.8782639503479 seconds ---
--- preheat0: 372.9902067184448 seconds ---
--- preheat1: 0.11191296577453613 seconds ---
--- with preheat again: 0.011079072952270508 seconds ---
```

**Comment by xgui3783** [comment]
some more update on the performance:

```sh
--- preheat-1: 297.6919231414795 seconds ---
--- preheat0: 297.8185453414917 seconds ---
--- preheat1: 0.12659120559692383 seconds ---
--- with preheat again: 0.01661086082458496 seconds ---
```

**Comment by dickscheid** [comment]
I am not sure if I fully understood the logic, will this affect the way that atlas objects are used to query data? Did you run/update the example notebook for fetching regional data?

**Comment by xgui3783** [comment]
> I am not sure if I fully understood the logic, will this affect the way that atlas objects are used to query data? Did you run/update the example notebook for fetching regional data?

The change in principle is a drop-in replacement. As far as the examples in ipynb, none are directly affected.

The issue, at least at HEAD at develop, is that on each `atlas.get_features` call, a new extractor is instantiated. For EbrainsRegionalDataset, this means:

- new network call to KG (can be cached)
- A large number of `atlas.selected_parcellation.decode_region` calls (which is the slowest part by far)
- instantiate a large number of EbrainsRegionalDataset

**Comment by xgui3783** [comment]
Maybe I can take a look at the issue again and come up with a more elegant solution.

There were a lot of misconception I had when I started working on this issue.

**Comment by xgui3783** [comment]
superceded by #64

**Pull request closed without merging**
