### PR TITLE
Test configured maps to get regions from parcellations

### PR DESCRIPTION
**Pull request by AhmetNSimsek**
The reasons for the test:

#332 and https://github.com/FZJ-INM1-BDA/siibra-python/issues/291

Additionally:
- monkey mebrains labelled
   - Pallidum
- fsaverage jba30 labelled
   - BrainStemMask left
   - BrainStemMask right

### CODE REVIEW

**Comment by AhmetNSimsek** [comment]
Note: The failing tests are exactly the reason this test is added for. Should be in main.

**Comment by xgui3783** [comment]
proposed remedy:

either:
- update appropriate tag siibra configuration and retrun test. or...
- create new tag on siibra configuration and bump version in this PR

**Comment by AhmetNSimsek** [comment]
Sebastian informed me that `BrainStemMask` cannot be a part of the region tree. But it was required for the creation of fsaverage surface map.
Options I see:
- `BrainStemMask` does not need to be in the map configuration.
- or we can add an exception case for the test
What do you think @dickscheid?

**Review by xgui3783 — APPROVED** [review]
looks good. but I would add CI test to brainscapes configuration, which makes more sense than e2e here.

**Comment by AhmetNSimsek** [comment]
> looks good. but I would add CI test to brainscapes configuration, which makes more sense than e2e here.

I agree that the proper place is brainscapes-configurations. But I think we need `siibra` for this check since the region names are not exact matches and there could be subset matches etc. `get_region` simplifies life a lot. We could import siibra in _ci to check... Thoughts?

**Comment by xgui3783** [comment]
> > looks good. but I would add CI test to brainscapes configuration, which makes more sense than e2e here.
> 
> I agree that the proper place is brainscapes-configurations. But I think we need `siibra` for this check since the region names are not exact matches and there could be subset matches etc. `get_region` simplifies life a lot. We could import siibra in _ci to check... Thoughts?

the keys in indicies *should* be an exact match to that of parcellation, no?

**Comment by xgui3783** [comment]
All the reason to have the CI on config, so that it can be caught as early
as possible?

**Comment by AhmetNSimsek** [comment]
What do you think of the following:
https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/commit/bcf09c2c1f1414d753a47138640c8b7901b58a55

**Comment by AhmetNSimsek** [comment]
Requires https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/merge_requests/87

**Comment by AhmetNSimsek** [comment]
TODO: add a field to maps for regions that are mapped but not represented in the parcellation, such as brain stem mask in fsaverage julich brain 3.

**Pull request merged**
